{{- if and .Values.gonogo.enabled (not .Values.rbac.disabled) -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "insights-agent.fullname" . }}-gonogo
  labels:
    app: insights-agent
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "insights-agent.fullname" . }}-gonogo-view
  labels:
    app: insights-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
  - kind: ServiceAccount
    name: {{ include "insights-agent.fullname" . }}-gonogo
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "insights-agent.fullname" . }}-view-secrets
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "insights-agent.fullname" . }}-gonogo-secrets-viewer
  labels:
    app: insights-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "insights-agent.fullname" . }}-view-secrets
subjects:
  - kind: ServiceAccount
    name: {{ include "insights-agent.fullname" . }}-gonogo
    namespace: {{ .Release.Namespace }}
{{- end -}}