apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mutillidae.fullname" . }}-ldap
  labels:
    {{- include "mutillidae.labels" . | nindent 4 }}
spec:
  {{- if not .Values.ldap.autoscaling.enabled }}
  replicas: {{ .Values.ldap.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "mutillidae.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: ldap
  template:
    metadata:
      {{- with .Values.ldap.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mutillidae.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: ldap
    spec:
      {{- with .Values.ldap.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mutillidae.ldap.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.ldap.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.ldap.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:ldap-{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.ldap.resources | nindent 12 }}
      {{- with .Values.ldap.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ldap.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ldap.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
