apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mutillidae.fullname" . }}-www
  labels:
    {{- include "mutillidae.labels" . | nindent 4 }}
spec:
  {{- if not .Values.www.autoscaling.enabled }}
  replicas: {{ .Values.www.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "mutillidae.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: www
  template:
    metadata:
      {{- with .Values.www.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mutillidae.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: www
    spec:
      {{- with .Values.www.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mutillidae.www.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.www.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.www.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:www-{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: http
          readinessProbe:
            tcpSocket:
              port: http
          resources:
            {{- toYaml .Values.www.resources | nindent 12 }}
      {{- with .Values.www.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.www.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.www.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
