apiVersion: v1
kind: Service
metadata:
  name: directory
  labels:
    {{- include "mutillidae.labels" . | nindent 4 }}
    app.kubernetes.io/component: ldap
spec:
  type: {{ .Values.ldap.service.type }}
  ports:
    - port: 389
      targetPort: ldap
      protocol: TCP
      name: ldap
  selector:
    {{- include "mutillidae.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ldap
